// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Interactions is an autogenerated mock type for the Interactions type
type Interactions struct {
	mock.Mock
}

// Verify provides a mock function with given fields: rawBody, headers, publicKey
func (_m *Interactions) Verify(rawBody []byte, headers http.Header, publicKey string) bool {
	ret := _m.Called(rawBody, headers, publicKey)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte, http.Header, string) bool); ok {
		r0 = rf(rawBody, headers, publicKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
