// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	slashcommands "github.com/wafer-bw/udx-discord-bot/disgoslash/slashcommands"
)

// Syncer is an autogenerated mock type for the Syncer type
type Syncer struct {
	mock.Mock
}

// Run provides a mock function with given fields: guildIDs, slashCommandMap
func (_m *Syncer) Run(guildIDs []string, slashCommandMap slashcommands.Map) error {
	ret := _m.Called(guildIDs, slashCommandMap)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, slashcommands.Map) error); ok {
		r0 = rf(guildIDs, slashCommandMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
