// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/wafer-bw/udx-discord-bot/app/models"
)

// Commands is an autogenerated mock type for the Commands type
type Commands struct {
	mock.Mock
}

// Run provides a mock function with given fields: interaction
func (_m *Commands) Run(interaction *models.InteractionRequest) (*models.InteractionResponse, error) {
	ret := _m.Called(interaction)

	var r0 *models.InteractionResponse
	if rf, ok := ret.Get(0).(func(*models.InteractionRequest) *models.InteractionResponse); ok {
		r0 = rf(interaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InteractionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.InteractionRequest) error); ok {
		r1 = rf(interaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
