// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interactions "github.com/wafer-bw/discobottest/app/interactions"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Execute provides a mock function with given fields: request
func (_m *Action) Execute(request *interactions.InteractionRequest) (*interactions.InteractionResponse, error) {
	ret := _m.Called(request)

	var r0 *interactions.InteractionResponse
	if rf, ok := ret.Get(0).(func(*interactions.InteractionRequest) *interactions.InteractionResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interactions.InteractionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*interactions.InteractionRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
